apiVersion: v1
kind: Pod
metadata:
  name: iperf-server
  labels:
    app: iperf
spec:
  affinity:
    podAntiAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 100
        podAffinityTerm:
          labelSelector:
            matchExpressions:
            - key: app
              operator: In
              values:
              - iperf
          topologyKey: kubernetes.io/hostname
  containers:
  - name: server
    image: iperf:latest
---
apiVersion: v1
kind: Pod
metadata:
  name: iperf-client
  labels:
    app: iperf
spec:
  affinity:
    podAntiAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 100
        podAffinityTerm:
          labelSelector:
            matchExpressions:
            - key: app
              operator: In
              values:
              - iperf
          topologyKey: kubernetes.io/hostname
  containers:
  - name: client
    image: iperf:latest
